spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/card
    username: root
    password: 6602
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture
        dialect:
  main:
    allow-bean-definition-overriding: true