spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${{secrets.RDS_HOST}}:${{secrets.RDS_PORT}}/${{secrets.DB_NAME}}
    username: ${{secrets.RDS_USERNAME}}
    password: ${{secrets.RDS_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
        dialect:
  main:
    allow-bean-definition-overriding: true

auth:
  jwt:
    secretKey: ${{secrets.JWT_SECRET_KEY}}
    accessExp: ${{secrets.JWT_ACCESS_EXP}}
    refreshExp: ${{secrets.JWT_REFRESH_EXP}}
    header: ${{secrets.JWT_HEADER}}
    prefix: ${{secrets.JWT_PREFIX}}

naver-cloud-sms:
  accessKey: ${{secrets.SMS_ACCESS_KEY}}
  secretKey: ${{secrets.SMS_SECRET_KEY}}
  serviceId: ${{secrets.SMS_SERVICE_ID}}
  senderPhone: ${{secrets.SMS_SENDER_PHONE}}

oauth:
  kakao:
    client-id: ${{secrets.KAKAO_CLIENT_ID}
    redirect-uri: ${{secrets.KAKAO_REDIRECT_URI}}
    client-secret: ${{secrets.KAKAO_CLIENT_SECRET}}
    scope:
      - profile_nickname
      - account_email


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: ${{secrets.SWAGGER_PATH}}
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match: /**

aws:
  access-key: ${{secrets.AWS_ACCESS_KEY_ID}}
  secret-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  s3:
    bucket: ${{secrets.AWS_BUCKET}}
    base-url: ${{secrets.AWS_BASE_URL}}
